import React, { useState } from 'react';
import { Link } from 'react-router';
import { motion } from 'framer-motion';
import ThemeToggle from '../components/ThemeToggle';
import { MovingBorderDemo } from '../components/ui/moving-border-demo';
import { Button } from '../components/ui/moving-border';
import { cn } from '../lib/utils';
import SkipCard from '../components/SkipCard';
import type { Skip } from '../constants/skips';
import { GradientButtonDemo } from '../components/ui/gradient-button-demo';
import SparklesHeader from '../components/SparklesHeader';

// This type mimics what would normally be generated by Route types
type ComponentProps = {
  params: {};
};

export default function Component({ params }: ComponentProps) {
  // Demo skip for showcasing the SkipCard
  const [selectedSkipDemo, setSelectedSkipDemo] = useState(false);

  const demoSkip: Skip = {
    id: 9999,
    size: 6,
    name: 'Demo Skip',
    description: 'This is a demonstration skip with a moving border when selected.',
    price_before_vat: 410,
    vat: 20,
    hire_period_days: 14,
    allows_heavy_waste: true,
    allowed_on_road: true,
    postcode: 'NR32',
    transport_cost: null,
    per_tonne_cost: null,
    area: null,
    forbidden: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    imageUrl: '/images/6.JPG',
  };

  return (
    <div className="min-h-screen bg-background text-foreground relative" data-author="Paul Doros">
      {/* Subtle sparkles effect at the top */}
      <SparklesHeader particleColor="var(--primary)" height="h-[200px]" particleDensity={30} />

      <div className="container mx-auto px-4 py-10">
        <motion.h1
          className="text-3xl font-bold mb-3 text-center mt-16"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          UI Components Demo
        </motion.h1>

        <p className="text-muted-foreground text-center mb-8">
          Explore the various UI components available in the RemWaste Skip Hire application.
        </p>

        <div className="mt-12 mb-6">
          <h2 className="text-2xl font-bold mb-4">Integration Examples</h2>
          <p className="mb-6 text-muted-foreground">
            Here are examples of how the moving border can be integrated into actual UI components.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="bg-card p-6 rounded-lg shadow-md">
              <h3 className="text-xl font-semibold mb-4">Card with Moving Border</h3>
              <div className="relative p-[1px] rounded-lg overflow-hidden">
                <div className="absolute inset-0 z-0">
                  <div className="absolute inset-0">
                    <Button
                      as="div"
                      containerClassName="w-full h-full"
                      className="opacity-0"
                      borderClassName="bg-[radial-gradient(var(--primary)_30%,transparent_70%)]"
                    >
                      <span></span>
                    </Button>
                  </div>
                </div>
                <div className="relative z-10 bg-card p-6 rounded-lg border border-border">
                  <h4 className="text-lg font-medium mb-2">Featured Content</h4>
                  <p className="text-muted-foreground text-sm mb-4">
                    This card has a subtle moving border effect to draw attention.
                  </p>
                  <button className="px-4 py-2 bg-primary text-primary-foreground rounded-md">
                    Learn More
                  </button>
                </div>
              </div>
            </div>

            <div className="bg-card p-6 rounded-lg shadow-md">
              <h3 className="text-xl font-semibold mb-4">Interactive Elements</h3>
              <div className="space-y-4">
                <div className="relative inline-block">
                  <Button
                    as="div"
                    containerClassName="w-full"
                    className="bg-background border-border"
                  >
                    <input
                      type="email"
                      placeholder="Enter email address"
                      className="bg-transparent outline-none px-4 w-full"
                    />
                  </Button>
                </div>

                <div className="flex justify-center my-6">
                  <Button
                    borderRadius="9999px"
                    containerClassName="w-12 h-12"
                    className="bg-primary text-primary-foreground flex items-center justify-center"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="w-5 h-5"
                    >
                      <path d="m5 12 5 5 9-9" />
                    </svg>
                  </Button>
                </div>
              </div>
            </div>
          </div>

          {/* SkipCard Demo Section */}
          <div className="mt-12">
            <h2 className="text-2xl font-bold mb-4">Skip Card With Moving Border</h2>
            <p className="mb-6 text-muted-foreground">
              Click the skip card to see the animated moving border effect in action.
            </p>

            <div className="flex flex-col items-center">
              <div className="max-w-md w-full">
                <SkipCard
                  skip={demoSkip}
                  isSelected={selectedSkipDemo}
                  onSelect={() => setSelectedSkipDemo(!selectedSkipDemo)}
                />
              </div>

              <div className="mt-8 bg-card p-4 rounded-lg border border-border">
                <h3 className="text-lg font-semibold mb-2">Implementation Details</h3>
                <p className="text-muted-foreground mb-3">
                  This skip card uses the moving border component to create a visually appealing
                  selected state:
                </p>
                <pre className="bg-muted p-3 rounded text-xs overflow-x-auto">
                  {`{isSelected && (
  <div className="absolute inset-0 z-0 pointer-events-none">
    <MovingBorder duration={4000} rx="12px" ry="12px">
      <div className="h-28 w-28 opacity-[0.7] 
           bg-[radial-gradient(var(--sky-500)_20%,
                             var(--blue-500)_30%,
                             var(--indigo-500)_45%,
                             transparent_65%)]" />
    </MovingBorder>
  </div>
)}`}
                </pre>
              </div>
            </div>
          </div>

          {/* GradientButton Demo Section */}
          <div className="mt-12">
            <h2 className="text-2xl font-bold mb-4">Gradient Button Component</h2>
            <p className="mb-6 text-muted-foreground">
              The GradientButton component provides beautiful gradient effects for your
              call-to-action buttons, with a special "proceed" variant that matches our theme
              colors.
            </p>

            <GradientButtonDemo />
          </div>
        </div>

        <div className="mt-12 text-center">
          <Link
            to="/skips"
            className="inline-block bg-primary text-primary-foreground px-6 py-3 rounded-md font-medium hover:bg-primary/90 transition-colors"
          >
            Go to Skip Selection Page
          </Link>
        </div>
      </div>

      {/* Theme toggle */}
      <div className="fixed top-4 right-4 z-50">
        <ThemeToggle />
      </div>
    </div>
  );
}
