import React, { useState } from 'react';
import { Link } from 'react-router';
import ThemeToggle from '../components/ThemeToggle';
import { Button } from '../components/ui/moving-border';
import { MovingBorder } from '../components/ui/moving-border';
import { cn } from '../lib/utils';
import type { Skip } from '../constants/skips';
import SkipCard from '../components/SkipCard';

// This type mimics what would normally be generated by Route types
type ComponentProps = {
  params: {};
};

export default function Component({ params }: ComponentProps) {
  const [selectedDemo, setSelectedDemo] = useState<string | null>(null);
  const [selectedSkipDemo, setSelectedSkipDemo] = useState(false);

  const demoSkip: Skip = {
    id: 9999,
    size: 6,
    name: 'Demo Skip',
    description: 'This is a demonstration skip with a moving border when selected.',
    price_before_vat: 410,
    vat: 20,
    hire_period_days: 14,
    allows_heavy_waste: true,
    allowed_on_road: true,
    postcode: 'NR32',
    transport_cost: null,
    per_tonne_cost: null,
    area: null,
    forbidden: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    imageUrl: '/images/6.JPG',
  };

  return (
    <div className="min-h-screen bg-background text-foreground p-4 md:p-8" data-author="Paul Doros">
      <nav className="mb-8">
        <Link to="/" className="text-primary hover:underline">
          ← Back to Home
        </Link>
      </nav>

      <h1 className="text-3xl font-bold mb-6">Moving Border Component Demo</h1>
      <p className="text-muted-foreground mb-12 max-w-2xl">
        This page showcases the versatile Moving Border component that can be applied to a variety
        of UI elements to create engaging, interactive experiences with minimal effort.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-12 mb-16">
        {/* Basic Button Examples */}
        <div className="bg-card p-6 rounded-lg border border-border">
          <h2 className="text-2xl font-semibold mb-4">Basic Buttons</h2>
          <p className="text-muted-foreground mb-6">
            Simple button implementations showing different sizes, shapes, and colors.
          </p>

          <div className="flex flex-wrap gap-6">
            <Button borderRadius="0.5rem" className="bg-primary text-primary-foreground px-4 py-2">
              Standard Button
            </Button>

            <Button
              borderRadius="9999px"
              className="bg-secondary text-secondary-foreground px-6 py-2"
            >
              Rounded Button
            </Button>

            <Button
              borderRadius="0.5rem"
              className="bg-destructive text-destructive-foreground px-4 py-2"
              borderClassName="bg-[radial-gradient(var(--destructive)_40%,transparent_70%)]"
            >
              Alert Button
            </Button>

            <Button
              borderRadius="9999px"
              containerClassName="w-12 h-12"
              className="bg-accent text-accent-foreground flex items-center justify-center"
            >
              <span className="text-xl">+</span>
            </Button>
          </div>
        </div>

        {/* Creative Implementation */}
        <div className="bg-card p-6 rounded-lg border border-border">
          <h2 className="text-2xl font-semibold mb-4">Creative Uses</h2>
          <p className="text-muted-foreground mb-6">
            Beyond buttons - using the moving border for forms, cards, and other elements.
          </p>

          <div className="space-y-6">
            <div className="relative">
              <Button
                as="div"
                containerClassName="w-full"
                className="bg-background border-border"
                borderClassName="bg-[radial-gradient(var(--primary)_30%,transparent_70%)]"
              >
                <input
                  type="text"
                  placeholder="Search..."
                  className="w-full p-2 bg-transparent outline-none"
                />
              </Button>
            </div>

            <div
              className={cn(
                'cursor-pointer relative p-[1px] rounded-lg overflow-hidden',
                selectedDemo === 'card' ? 'z-10' : ''
              )}
              onClick={() => setSelectedDemo(selectedDemo === 'card' ? null : 'card')}
            >
              {selectedDemo === 'card' && (
                <div className="absolute inset-0 z-0 pointer-events-none">
                  <MovingBorder duration={4000} rx="12px" ry="12px">
                    <div
                      className="h-28 w-28 opacity-[0.7] 
                         bg-[radial-gradient(var(--sky-500)_20%,
                                           var(--blue-500)_30%,
                                           var(--indigo-500)_45%,
                                           transparent_65%)]"
                    />
                  </MovingBorder>
                </div>
              )}
              <div className="relative z-10 bg-card p-6 rounded-lg border border-border">
                <h3 className="text-lg font-medium mb-2">Interactive Card</h3>
                <p className="text-muted-foreground text-sm">
                  Click me to see the moving border effect in action!
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Customization Showcase */}
      <div className="mb-16">
        <h2 className="text-2xl font-semibold mb-4">Customize the Effect</h2>
        <p className="text-muted-foreground mb-6">
          The MovingBorder component can be customized in many ways - color, speed, size, and more.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Different Colors */}
          <div className="p-6 bg-card rounded-lg border border-border">
            <h3 className="text-lg font-medium mb-4">Color Variations</h3>
            <div className="space-y-4">
              <Button
                className="w-full bg-background border-border"
                borderClassName="bg-[radial-gradient(var(--primary)_30%,transparent_70%)]"
              >
                Primary Gradient
              </Button>

              <Button
                className="w-full bg-background border-border"
                borderClassName="bg-[radial-gradient(var(--destructive)_30%,transparent_70%)]"
              >
                Destructive Gradient
              </Button>

              <Button
                className="w-full bg-background border-border"
                borderClassName="bg-[radial-gradient(var(--cyan-500)_25%,var(--blue-500)_40%,transparent_70%)]"
              >
                Multi-Color Gradient
              </Button>
            </div>
          </div>

          {/* Different Speeds */}
          <div className="p-6 bg-card rounded-lg border border-border">
            <h3 className="text-lg font-medium mb-4">Animation Speed</h3>
            <div className="space-y-4">
              <Button className="w-full bg-background border-border" duration={2000}>
                Fast (2s)
              </Button>

              <Button className="w-full bg-background border-border" duration={4000}>
                Medium (4s)
              </Button>

              <Button className="w-full bg-background border-border" duration={8000}>
                Slow (8s)
              </Button>
            </div>
          </div>

          {/* Different Shapes */}
          <div className="p-6 bg-card rounded-lg border border-border">
            <h3 className="text-lg font-medium mb-4">Shape Variations</h3>
            <div className="space-y-4">
              <Button borderRadius="0" className="w-full bg-background border-border">
                Square Corners
              </Button>

              <Button borderRadius="0.5rem" className="w-full bg-background border-border">
                Rounded Corners
              </Button>

              <Button borderRadius="9999px" className="w-full bg-background border-border">
                Fully Rounded
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* SkipCard Integration */}
      <div className="mb-16">
        <h2 className="text-2xl font-semibold mb-4">Real-World Integration: Skip Card</h2>
        <p className="text-muted-foreground mb-6">
          See how the MovingBorder component is integrated into the SkipCard component to create an
          appealing selected state that draws user attention.
        </p>

        <div className="flex flex-col items-center">
          <div className="max-w-md w-full">
            <SkipCard
              skip={demoSkip}
              isSelected={selectedSkipDemo}
              onSelect={() => setSelectedSkipDemo(!selectedSkipDemo)}
            />
          </div>

          <div className="mt-8 p-6 bg-card rounded-lg border border-border max-w-2xl w-full">
            <h3 className="text-lg font-medium mb-2">How It Works</h3>
            <p className="text-muted-foreground mb-4">
              The moving border effect is conditionally applied when the skip is selected, creating
              a visually appealing highlight that draws attention to the user's choice.
            </p>

            <div className="bg-muted p-4 rounded-lg overflow-x-auto">
              <pre className="text-xs">
                {`{isSelected && (
  <div className="absolute inset-0 z-0 pointer-events-none">
    <MovingBorder duration={4000} rx="12px" ry="12px">
      <div className="h-28 w-28 opacity-[0.7] 
           bg-[radial-gradient(var(--sky-500)_20%,
                             var(--blue-500)_30%,
                             var(--indigo-500)_45%,
                             transparent_65%)]" />
    </MovingBorder>
  </div>
)}`}
              </pre>
            </div>
          </div>
        </div>
      </div>

      {/* Call to Action */}
      <div className="text-center mb-16">
        <h2 className="text-2xl font-semibold mb-4">Try It In Your Project</h2>
        <p className="text-muted-foreground mb-6 max-w-xl mx-auto">
          The MovingBorder component is flexible and easy to integrate into your own designs. Check
          out the implementation and start using it today.
        </p>

        <div className="flex flex-wrap justify-center gap-4">
          <Link
            to="/skips"
            className="inline-block bg-primary text-primary-foreground px-6 py-3 rounded-md font-medium hover:bg-primary/90 transition-colors"
          >
            See It In Action
          </Link>

          <Link
            to="/examples"
            className="inline-block bg-secondary text-secondary-foreground px-6 py-3 rounded-md font-medium hover:bg-secondary/90 transition-colors"
          >
            More Examples
          </Link>
        </div>
      </div>

      <footer className="text-center text-muted-foreground">
        <p>
          Designed by{' '}
          <a href="https://pauldoros.site" className="text-primary hover:underline">
            Paul Doros
          </a>
        </p>
      </footer>

      {/* Theme toggle */}
      <div className="fixed top-4 right-4">
        <ThemeToggle />
      </div>
    </div>
  );
}
