import React from 'react';
import { Link } from 'react-router';
import ThemeToggle from '../components/ThemeToggle';
import {
  SparklesPreview,
  SparklesPreviewDark,
  SparklesPreviewColorful,
  SparklesPreviewThemed,
} from '../components/ui/sparkles-demo';
import { GradientButton } from '../components/ui/gradient-button';
import { cn } from '../lib/utils';

// This type mimics what would normally be generated by Route types
type ComponentProps = {
  params: {};
};

export default function Component({ params }: ComponentProps) {
  return (
    <div className="min-h-screen bg-background text-foreground" data-author="Paul Doros">
      <nav className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-md shadow-sm">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/" className="text-primary hover:text-primary/80 font-medium">
            ← Back to Home
          </Link>
          <div className="flex gap-4 items-center">
            <Link to="/examples" className="text-primary hover:text-primary/80">
              Component Examples
            </Link>
            <ThemeToggle />
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-4 py-24">
        <div className="mb-16 text-center">
          <h1 className="text-4xl font-bold mb-4">Sparkles Component Demo</h1>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            The Sparkles component creates beautiful particle effects that can be customized to
            match your theme. Scroll down to see different variations and customization options.
          </p>
        </div>

        <div className="space-y-24">
          {/* Default Sparkles */}
          <section>
            <h2 className="text-2xl font-bold mb-6">Standard Sparkles</h2>
            <p className="text-muted-foreground mb-8">
              The default sparkles effect with dense particles and subtle animations.
            </p>
            <div className="rounded-xl overflow-hidden shadow-xl">
              <SparklesPreview />
            </div>
          </section>

          {/* Dark Sparkles */}
          <section>
            <h2 className="text-2xl font-bold mb-6">Full Page Sparkles</h2>
            <p className="text-muted-foreground mb-8">
              Particles that fill the entire container with a dark background for maximum contrast.
            </p>
            <div className="rounded-xl overflow-hidden shadow-xl">
              <SparklesPreviewDark />
            </div>
          </section>

          {/* Colorful Sparkles */}
          <section>
            <h2 className="text-2xl font-bold mb-6">Colorful Sparkles</h2>
            <p className="text-muted-foreground mb-8">
              Custom colored particles with text treatment for a unique visual effect.
            </p>
            <div className="rounded-xl overflow-hidden shadow-xl">
              <SparklesPreviewColorful />
            </div>
          </section>

          {/* Themed Sparkles */}
          <section>
            <h2 className="text-2xl font-bold mb-6">Themed Sparkles</h2>
            <p className="text-muted-foreground mb-8">
              Particles using your theme colors with a gradient background and interactive buttons.
            </p>
            <div className="rounded-xl overflow-hidden shadow-xl">
              <SparklesPreviewThemed />
            </div>
          </section>

          {/* Implementation Guide */}
          <section className="bg-card p-8 rounded-xl border border-border">
            <h2 className="text-2xl font-bold mb-6">How to Use</h2>
            <div className="space-y-6">
              <div>
                <h3 className="text-xl font-semibold mb-3">1. Import the Component</h3>
                <pre className="bg-muted p-4 rounded-md overflow-x-auto">
                  <code className="text-sm">
                    import {'{'} SparklesCore {'}'} from './components/ui/sparkles';
                  </code>
                </pre>
              </div>

              <div>
                <h3 className="text-xl font-semibold mb-3">2. Basic Implementation</h3>
                <pre className="bg-muted p-4 rounded-md overflow-x-auto">
                  <code className="text-sm">{`<div className="h-[500px] relative">
  <SparklesCore
    id="mySparkles"
    background="transparent"
    minSize={0.6}
    maxSize={1.4}
    particleDensity={100}
    className="w-full h-full"
    particleColor="#FFFFFF"
    speed={1}
  />
  <h1 className="relative z-20 text-center text-white">Your Content Here</h1>
</div>`}</code>
                </pre>
              </div>

              <div>
                <h3 className="text-xl font-semibold mb-3">3. Customization Options</h3>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li>
                    <strong>background</strong>: Set the background color (or "transparent" to use
                    container's background)
                  </li>
                  <li>
                    <strong>minSize/maxSize</strong>: Control the size range of particles
                  </li>
                  <li>
                    <strong>particleDensity</strong>: Number of particles (higher = more particles)
                  </li>
                  <li>
                    <strong>particleColor</strong>: Color of the particles (accepts hex, rgb, or CSS
                    variables)
                  </li>
                  <li>
                    <strong>speed</strong>: Animation speed for particles
                  </li>
                </ul>
              </div>
            </div>
          </section>

          {/* Call to Action */}
          <div className="text-center">
            <h2 className="text-2xl font-bold mb-6">Ready to Implement?</h2>
            <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">
              Add the Sparkles component to your own page or check out other components in our
              library.
            </p>
            <div className="flex gap-4 justify-center">
              <Link
                to="/skips"
                className={cn(
                  'gradient-button inline-flex items-center justify-center',
                  'rounded-[11px] min-w-[132px] px-9 py-4',
                  'text-base leading-[19px] font-bold text-white',
                  'bg-gradient-to-r from-primary to-blue-500 hover:from-blue-500 hover:to-indigo-500',
                  'text-primary-foreground'
                )}
              >
                See Skip Booking
              </Link>
              <Link
                to="/examples"
                className={cn(
                  'gradient-button inline-flex items-center justify-center',
                  'rounded-[11px] min-w-[132px] px-9 py-4',
                  'text-base leading-[19px] font-bold',
                  'border-2 border-primary bg-transparent hover:bg-primary/10',
                  'text-primary hover:text-primary'
                )}
              >
                View More Components
              </Link>
            </div>
          </div>
        </div>
      </div>

      <footer className="bg-card border-t border-border mt-24 py-8">
        <div className="container mx-auto px-4 text-center">
          <p className="text-muted-foreground">
            Designed by{' '}
            <a href="https://pauldoros.site" className="text-primary hover:underline">
              Paul Doros
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}
